### ISSUE TITLE
@particle/device-constants is no longer public?

### ISSUE THREAD

**Issue by jlkalberer** [particle-iot/binary-version-reader#47]
The `@particle/device-constants` package is locked to node "12.x"

I can't put out a pull request to fix it since I assume it is now internal and it's making NPM install fail.

**Comment by busticated** [comment]
hey there - sorry for the delay - i'm guessing you're using `yarn` and you've probably figured this out already by now but fwiw you can skip the `engines` check with the `--ignore-engines` flag ([docs](https://classic.yarnpkg.com/en/docs/cli/install#yarn-install---ignore-engines-)).

in general the `engines` field is considered advisory unless you opt-in to strict enforcement ([docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines)) 👍
